
SEED_SENTENCES: list[dict] = [
    # daily_life
    {"domain": "daily_life", "text": "أنا رايح السوق دلوقتي، عايز حاجة؟"},
    {"domain": "daily_life", "text": "الجو حر جداً النهارده، مش طايق أقعد برة."},
    {"domain": "daily_life", "text": "فضلوا تلت كيلو برتقال وكيلو طماطم، خدهم بكام؟"},
    {"domain": "daily_life", "text": "كلمت الجيران وقالوا الضوضاء من الدور الخامس."},
    {"domain": "daily_life", "text": "النور اتقطع من امبارح ولحد دلوقتي، مش عارف أعمل إيه."},
    {"domain": "daily_life", "text": "وصلت البيت متأخر عشان الزحمة كانت بجنان في الطريق."},
    {"domain": "daily_life", "text": "حشتري الجرنان وأرجع على طول."},
    {"domain": "daily_life", "text": "محتاج أصلح الموبايل بتاعي، الشاشة اتكسرت."},
    {"domain": "daily_life", "text": "البنك مقفول دلوقتي، هروح بكرة الصبح."},
    {"domain": "daily_life", "text": "مين بيجرس ده؟ إيه الوقت ده ليه؟"},
    {"domain": "daily_life", "text": "الكهربا غالية جداً المرة دي، الفاتورة جت فوق التلاتمية جنيه."},
    {"domain": "daily_life", "text": "فضل شوية مية في الجالون، هنعدي بيها."},
    {"domain": "daily_life", "text": "الجزارة بدري النهارده، حروح آخر النهار عشان يبقى فيه لحمة."},
    {"domain": "daily_life", "text": "المواعيد مش بتتأجل، لازم تكون هناك الساعة عشرة بالظبط."},
    {"domain": "daily_life", "text": "عايز أخد إجازة بكرة ولكن الشغل مش بيسمح."},
    {"domain": "daily_life", "text": "حطيت المفتاح في الدرج بتاع المدخل."},
    {"domain": "daily_life", "text": "البقالة الجديدة دي أرخص بكتير من اللي قبلها."},
    {"domain": "daily_life", "text": "ماعرفتش أنام من الحر، لفيت في السرير طول الليل."},
    {"domain": "daily_life", "text": "حنعزم الناس الجمعة الجاية، هيبقى فيه ناس كتير."},
    {"domain": "daily_life", "text": "سرقوا الشنطة من جنبي في الزحمة ومعرفتش أحد."},

    #  family_home
    {"domain": "family_home", "text": "ماما طلبت مني أجيب الغسيل من فوق."},
    {"domain": "family_home", "text": "أخويا بيلعب في الكمبيوتر من الصبح لحد دلوقتي ومش بيصحى."},
    {"domain": "family_home", "text": "بابا مش هيجي بدري النهارده، عنده اجتماع."},
    {"domain": "family_home", "text": "هتعملوا إيه في عيد الميلاد؟ هنعمل حفلة ولا بس أكل؟"},
    {"domain": "family_home", "text": "أنا اللي هغسل الأطباق، إنت روح ذاكر."},
    {"domain": "family_home", "text": "الأكل على النار، مش هيتأخر، نص ساعة وتنزلوا تتغدوا."},
    {"domain": "family_home", "text": "الطفل ده بيعيط من نص ساعة، مش عارف إيه اللي بيحصله."},
    {"domain": "family_home", "text": "لو حاجة محتاجينها من السوق، ادوني قايمة دلوقتي قبل ما أنزل."},
    {"domain": "family_home", "text": "الأوضة مش منظفة خالص، امتى هتلمها يا عم؟"},
    {"domain": "family_home", "text": "إحنا محتاجين نشتري تلاجة جديدة، دي بقالها عشر سنين."},
    {"domain": "family_home", "text": "ست الكل عاملة كشري وسلطة، تعالوا الأكل اتحضر."},
    {"domain": "family_home", "text": "مش هقدر أيجي معاكوا المرة دي، عندي شغل ضروري."},
    {"domain": "family_home", "text": "هتشتروا العفش الجديد من فين؟ قولوا سيف الدين أحسن من موبيليا."},
    {"domain": "family_home", "text": "الولاد خلصوا الامتحانات وعايزين يروحوا شرم."},
    {"domain": "family_home", "text": "أنا تعبان من الشغل، خليني أرتاح شوية قبل العشاء."},

    # food_cafe
    {"domain": "food_cafe", "text": "إيه اللي بتاكله النهارده، في حاجة حلوة؟"},
    {"domain": "food_cafe", "text": "عايز كشري برجل واحدة وكتشب زيادة."},
    {"domain": "food_cafe", "text": "القهوة بتاعتهم حلوة جداً، بس تقيلة شوية."},
    {"domain": "food_cafe", "text": "جبت فول ومدمس من أبو طارق، ده أحسن فول في القاهرة."},
    {"domain": "food_cafe", "text": "الحمام المحشي دي بتاعتها زي السحر، بتحطله إيه؟"},
    {"domain": "food_cafe", "text": "عايزين حاجة ساقعة؟ في عصير قصب من جنب المسجد."},
    {"domain": "food_cafe", "text": "السمك النهارده طازة، خدنا كيلو بلطي وشوينا."},
    {"domain": "food_cafe", "text": "ماكلتش من الصبح ومعدتي بتوجعني، فين أقرب كافيه؟"},
    {"domain": "food_cafe", "text": "اللحمة دي مش اتشوّت كويس، لازم تفضل تانية عشر دقيقة."},
    {"domain": "food_cafe", "text": "أنا شايفة نطلب بيتزا النهارده، الجو بارد ومناسب."},
    {"domain": "food_cafe", "text": "الرقي اللي اشتريناه ده حلو جداً، ربنا يباركلك."},
    {"domain": "food_cafe", "text": "عمل لنا كنافة بالقشطة وشاي بالنعنع وتمام."},
    {"domain": "food_cafe", "text": "المطعم ده زحمة دايماً بالليل، أحسن ناكل بدري."},
    {"domain": "food_cafe", "text": "حطيت تاني كمون وكزبرة وطعم الحساء اتغير تماماً."},
    {"domain": "food_cafe", "text": "الكفتة بتاعتك أطعم من أي حاجة بيبيعوها في الكافيه."},

    #  transport 
    {"domain": "transport", "text": "المترو بعد طلعت حرب، هنزل طلعت حرب وتاكسي."},
    {"domain": "transport", "text": "ياعم التاكسي، روح شارع جامعة الدول، عارفه؟"},
    {"domain": "transport", "text": "الأتوبيس رقم اتنين وأربعين بيروح فين بالظبط؟"},
    {"domain": "transport", "text": "الزحمة على كوبري أكتوبر واقفة من ساعة، روح كورنيش النيل."},
    {"domain": "transport", "text": "عشرة جنيه ومش أكتر، ده مش زيادة على المسافة دي؟"},
    {"domain": "transport", "text": "المكروباص اللي رايح مدينة نصر بيقف فين بالظبط؟"},
    {"domain": "transport", "text": "نزلت غلط، المحطة الجاية دي هي اللي محتاجها."},
    {"domain": "transport", "text": "في باركينج قريب ولا لازم أحط العربية في الشارع؟"},
    {"domain": "transport", "text": "التاكسي مكسور التكييف، ممكن تنزل الشباك شوية؟"},
    {"domain": "transport", "text": "طول الطريق وعدل في شارع التحرير لحد ما تلاقي إشارة حمرا."},

    # work_school 
    {"domain": "work_school", "text": "الاجتماع اتأجل للأسبوع الجاي، فيه مشكلة في الجدول."},
    {"domain": "work_school", "text": "المشروع ده محتاج تلات أيام على الأقل عشان يخلص."},
    {"domain": "work_school", "text": "الأستاذ محمد عنده امتحان مفاجئ بكرة، ذاكرتوا؟"},
    {"domain": "work_school", "text": "لازم نسلّم التقرير آخر الأسبوع ولو مش خلص."},
    {"domain": "work_school", "text": "معاكيش ورقة الامتحان اللي فات عشان أشوف غلطاتي؟"},
    {"domain": "work_school", "text": "المدير عايز يشوف الأرقام قبل ما يعمل القرار."},
    {"domain": "work_school", "text": "خدت إجازة مرضية النهارده عشان كنت تعبان."},
    {"domain": "work_school", "text": "فيه ميتنج على الزووم الساعة اتنين، ماتنساش."},
    {"domain": "work_school", "text": "ما قدرتش أرد على الإيميل بدري، كنت في شغل تاني."},
    {"domain": "work_school", "text": "الفصل ده فيه خمسة وأربعين طالب والفصل ضيق على الآخر."},

    #  emotions_opinions 
    {"domain": "emotions_opinions", "text": "والله مبسوط جداً، النهارده يوم من أحسن الأيام."},
    {"domain": "emotions_opinions", "text": "مش فاهم ليه الناس بتعمل كده، بجد محيرني."},
    {"domain": "emotions_opinions", "text": "زعلان منك، كنت المفروض تخبرني من الأول."},
    {"domain": "emotions_opinions", "text": "صراحة الكلام ده مش منطقي خالص، مين اللي قاله؟"},
    {"domain": "emotions_opinions", "text": "أنا مع الفكرة دي مية بالمية، هي اللي هتنفع."},
    {"domain": "emotions_opinions", "text": "خايف من الامتحان بس هحاول أذاكر كويس."},
    {"domain": "emotions_opinions", "text": "الخبر ده صدمني جداً، ما توقعتوش."},
    {"domain": "emotions_opinions", "text": "مبسوطة بالهدية دي، جميلة جداً وما توقعتهاش."},
    {"domain": "emotions_opinions", "text": "مش مقتنع بالقرار ده بس هتبعه لأن الأغلبية وافقت."},
    {"domain": "emotions_opinions", "text": "تعبت من الحالة دي، محتاج أغير حاجة في حياتي."},

    #  phone_calls 
    {"domain": "phone_calls", "text": "ألو، آلو، تسمعني ولا فيه مشكلة في الشبكة؟"},
    {"domain": "phone_calls", "text": "أهلاً يا هاني، كنت بفكر فيك دلوقتي، إيه أخبارك؟"},
    {"domain": "phone_calls", "text": "كلمني لما توصل عشان أنزل أفتحلك الباب."},
    {"domain": "phone_calls", "text": "بابا بيعمل إيه؟ سلّم عليه وقوله إننا بخير."},
    {"domain": "phone_calls", "text": "عايزك تيجي بكرة الصبح لو معاك وقت."},
    {"domain": "phone_calls", "text": "مش قادر أحضر النهارده، ممكن نأجله للبعد بكرة؟"},
    {"domain": "phone_calls", "text": "الخط بيقطع معاك، هكلمك تاني من مكان تاني."},
    {"domain": "phone_calls", "text": "جدتك سألت عليك، قالت امتى هييجي يزورنا."},
    {"domain": "phone_calls", "text": "البيانات خلصت على الموبايل، هبعتلك على الواي فاي."},
    {"domain": "phone_calls", "text": "معلش ألو، صوتي مسمعش كويس؟ أنا هنا بسمعك."},

    # religion_daily 
    {"domain": "religion_daily", "text": "إن شاء الله هيتعدل الجو بكرة."},
    {"domain": "religion_daily", "text": "الحمد لله على كل حال، كل حاجة بخير."},
    {"domain": "religion_daily", "text": "ربنا يسهل وتعدي بسلامة يا رب."},
    {"domain": "religion_daily", "text": "ماشي يا عم، ربنا يخليك وتيجي بالسلامة."},
    {"domain": "religion_daily", "text": "بسم الله قبل ما نبدأ في الأكل."},
    {"domain": "religion_daily", "text": "الله يرحمه، كان راجل طيب جداً."},
    {"domain": "religion_daily", "text": "يسلم إيدك على الأكل الحلو ده."},
    {"domain": "religion_daily", "text": "ربنا يكرمك يا عم، متشكر جداً."},
    {"domain": "religion_daily", "text": "إن شاء الله تكون صحتك بتتحسن بسرعة."},
    {"domain": "religion_daily", "text": "والله أنا ما عرفتش أعمل غير كده، ده اللي قدرت عليه."},

    #  numbers_mixed 
    {"domain": "numbers_mixed", "text": "السعر اتغير، دلوقتي بقى مية وخمسين بدل المية."},
    {"domain": "numbers_mixed", "text": "الاجتماع الساعة عشرة والنص في نفس المكان."},
    {"domain": "numbers_mixed", "text": "عندي موعد الدكتور يوم الأربعاء الساعة اتنين."},
    {"domain": "numbers_mixed", "text": "اشتريت تلات حاجات وحساب الكاشير طلع أربعة."},
    {"domain": "numbers_mixed", "text": "في تلاتين طالب في الفصل ده بس غاب عشرة النهارده."},
    {"domain": "numbers_mixed", "text": "المشوار ده مش هياخد أكتر من ربع ساعة عادي."},
    {"domain": "numbers_mixed", "text": "الراتب بقى ألفين وخمسمية بعد الزيادة."},
    {"domain": "numbers_mixed", "text": "حجزت أوضة في الفندق من خمستاشر لتسعتاشر."},
    {"domain": "numbers_mixed", "text": "السيارة بقالها ست سنين ولسه شغالة تمام."},
    {"domain": "numbers_mixed", "text": "دفعت ثلاثة وعشرين جنيه في الفاتورة دي بس."},

    #  slang_expressions 
    {"domain": "slang_expressions", "text": "يسطا، ده مش معقول خالص، إيه ده بجد؟"},
    {"domain": "slang_expressions", "text": "عال العال، كده تمام، إنت فاهمها صح."},
    {"domain": "slang_expressions", "text": "يابني، إنت بتتكلم في إيه بالظبط؟"},
    {"domain": "slang_expressions", "text": "أيوه، ده اللي بقوله من الأول، متأخرين قوي."},
    {"domain": "slang_expressions", "text": "ماشي يا عم، خليها عليّ، أنا هتصرف."},
    {"domain": "slang_expressions", "text": "بلاها، مش محتاجين الموضوع ده دلوقتي."},
    {"domain": "slang_expressions", "text": "هو ده الكلام، كده بقى أحسن بكتير من الأول."},
    {"domain": "slang_expressions", "text": "تقيل شوية الكلام ده، فكر كويس قبل ما تقول."},
    {"domain": "slang_expressions", "text": "مش شايل همها، ده مش أكتر من مزحة."},
    {"domain": "slang_expressions", "text": "تمام يا صاحبي، شكراً على التعب، ربنا يجازيك."},
    # Additional sentences for expansion
    {"domain": "daily_life", "text": "السوق مزدحم النهارده، هاخد وقت طويل."},
    {"domain": "daily_life", "text": "نسيت المفتاح في البيت، لازم أرجع."},
    {"domain": "daily_life", "text": "القهوة باردة، هسخنها شوية."},
    {"domain": "daily_life", "text": "الجريدة جت متأخرة النهارده."},
    {"domain": "daily_life", "text": "الجيران بيعملوا صوت عالي جداً."},
    {"domain": "family_home", "text": "أبويا قال ييجي متأخر النهارده."},
    {"domain": "family_home", "text": "أختي بتذاكر للامتحان كويس."},
    {"domain": "family_home", "text": "الأكل جاهز، تعالى ناكل."},
    {"domain": "family_home", "text": "الغرفة مرتبة تمام النهارده."},
    {"domain": "family_home", "text": "بابا بيحب يشاهد الأخبار كل يوم."},
    {"domain": "food_cafe", "text": "القهوة هنا لذيذة جداً."},
    {"domain": "food_cafe", "text": "أحب أطلب فول مع الخبز."},
    {"domain": "food_cafe", "text": "الكشري هنا أحسن من التاني."},
    {"domain": "food_cafe", "text": "الساندويتش دي رخيصة وكويسة."},
    {"domain": "food_cafe", "text": "المشروب بارد تمام."},
    {"domain": "transport", "text": "التاكسي ده بيروح فين؟"},
    {"domain": "transport", "text": "المترو مزدحم الصبح."},
    {"domain": "transport", "text": "الأتوبيس متأخر النهارده."},
    {"domain": "transport", "text": "السائق ده ماهر جداً."},
    {"domain": "transport", "text": "الطريق ده طويل شوية."},
    {"domain": "work_school", "text": "الدرس صعب النهارده."},
    {"domain": "work_school", "text": "المدير قال ييجي غداً."},
    {"domain": "work_school", "text": "الواجب كتير اليوم."},
    {"domain": "work_school", "text": "الزملاء بيساعدوني كويس."},
    {"domain": "work_school", "text": "الاجتماع مهم جداً."},
    {"domain": "emotions_opinions", "text": "أنا سعيد بالنتيجة دي."},
    {"domain": "emotions_opinions", "text": "الفيلم ده مش حلو."},
    {"domain": "emotions_opinions", "text": "أنا متعب من الشغل."},
    {"domain": "emotions_opinions", "text": "الأخبار دي محزنة."},
    {"domain": "emotions_opinions", "text": "أنا متحمس للغد."},
    {"domain": "phone_calls", "text": "ألو، أنا سمعت صوتك."},
    {"domain": "phone_calls", "text": "كيف حالك يا صديقي؟"},
    {"domain": "phone_calls", "text": "هكلمك لما أوصل."},
    {"domain": "phone_calls", "text": "الخط ضعيف هنا."},
    {"domain": "phone_calls", "text": "سلّم على العيلة."},
    {"domain": "religion_daily", "text": "ربنا يساعدنا."},
    {"domain": "religion_daily", "text": "الحمد لله دائماً."},
    {"domain": "religion_daily", "text": "إن شاء الله كل حاجة تمام."},
    {"domain": "religion_daily", "text": "ربنا يرحم الجميع."},
    {"domain": "religion_daily", "text": "شكراً لك يا رب."},
    {"domain": "numbers_mixed", "text": "الساعة تلاتة الآن."},
    {"domain": "numbers_mixed", "text": "اشتريت خمس تفاحات."},
    {"domain": "numbers_mixed", "text": "الفاتورة مئتين جنيه."},
    {"domain": "numbers_mixed", "text": "يوم السابع من الشهر."},
    {"domain": "numbers_mixed", "text": "عمري ثلاثين سنة."},
    {"domain": "slang_expressions", "text": "ده كلام فارغ."},
    {"domain": "slang_expressions", "text": "أنا فاهم تمام."},
    {"domain": "slang_expressions", "text": "مش هقول حاجة."},
    {"domain": "slang_expressions", "text": "تمام يا راجل."},
    {"domain": "slang_expressions", "text": "على فكرة، ده مهم."},
]


def get_seed_sentences() -> list[dict]:
    """Return all seed sentences with IDs and length metadata attached."""
    result = []
    for i, item in enumerate(SEED_SENTENCES):
        words = item["text"].split()
        wc = len(words)
        if wc <= 8:
            bucket = "short"
        elif wc <= 18:
            bucket = "medium"
        else:
            bucket = "long"
        result.append({
            "id":            f"seed_{i:04d}",
            "text":          item["text"],
            "domain":        item["domain"],
            "length_bucket": bucket,
            "word_count":    wc,
            "char_count":    len(item["text"]),
            "source":        "seed_corpus",
        })
    return result